// Packs the recorded effects in assets/sfx/*.mp3 into src/audio/samples.data.js
// (base64 strings), so the bundle carries them itself: a single-file build or
// a host that serves only the script still has them, and a plain
// `esbuild src/main.js --bundle` needs no loader for .mp3. tools/build.mjs runs
// it; run it by hand after changing assets/sfx (assets/sfx/CREDITS.md lists
// where each one comes from).
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Writes the module (only when it changes); returns how many samples and bytes it holds. */
export function embedSfx() {
  const dir = join(root, 'assets/sfx'), out = join(root, 'src/audio/samples.data.js');
  if (!existsSync(dir)) return { n: 0, bytes: 0 };
  const files = readdirSync(dir).filter((f) => f.endsWith('.mp3')).sort();
  let bytes = 0;
  const lines = files.map((f) => {
    const b = readFileSync(join(dir, f));
    bytes += b.length;
    return `  ${JSON.stringify(f.slice(0, -4))}: '${b.toString('base64')}',`;
  });
  const src = [
    '// Generated by tools/sfx-embed.mjs from assets/sfx/*.mp3 — do not edit by hand.',
    '// The recorded layers under the synthesised effects (see samples.js); every one',
    '// is CC0 (assets/sfx/CREDITS.md says where each comes from).',
    'export const SAMPLE_DATA = {',
    ...lines,
    '};',
    '',
  ].join('\n');
  const old = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (old !== src) writeFileSync(out, src);
  return { n: files.length, bytes };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { n, bytes } = embedSfx();
  console.log(`embedded ${n} samples (${(bytes / 1024).toFixed(0)} KB) into src/audio/samples.data.js`);
}
